name: Build & Deploy .de website
on:
    push:
        branches:
        - main
    pull_request:
      types: [opened, synchronize, reopened]

jobs:
    build:
        runs-on: ubuntu-latest
        name: Build
        steps:
          - uses: actions/checkout@v4
          - name: Enable corepack
            run: corepack enable
          - name: Use Node.js
            uses: actions/setup-node@v4
          - name: Build static
            working-directory: de
            run: |
              yarn install
              yarn generate
          - name: Create site artefact
            uses: actions/upload-artifact@v4
            with:
                name: website-de
                path: de/.output
    deploy:
        permissions:
          actions: read # Only required for private GitHub Repo
          contents: read
          deployments: write
          pull-requests: write
        runs-on: ubuntu-latest
        needs: build
        name: Deploy
        steps:
          - uses: actions/checkout@v4
          - name: Download site artefact
            uses: actions/download-artifact@v4
            with:
                name: website-de
                path: .output
          - name: Deploy to Cloudflare Pages
            uses: andykenward/github-actions-cloudflare-pages@v2.3.0
            id: pages
            with:
              cloudflare-api-token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
              cloudflare-account-id: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
              cloudflare-project-name: ${{ vars.CLOUDFLARE_PROJECT_NAME_DE }}
              directory: .output/public
              github-token: ${{ secrets.GITHUB_TOKEN }}
              github-environment: ${{ vars.CLOUDFLARE_PROJECT_NAME_DE }} ${{ (github.ref == 'refs/heads/main' && '(Production)') || '(Preview)' }}