name: Build & Deploy .de website
on:
    push:
        branches:
        - main
    pull_request:
      types: [opened, synchronize, reopened]

jobs:
    build:
        runs-on: ubuntu-latest
        name: Build
        steps:
          - uses: actions/checkout@v4
          - name: Enable corepack
            run: corepack enable
          - name: Use Node.js
            uses: actions/setup-node@v4
          - name: Build static
            working-directory: de
            run: |
              yarn install
              yarn generate
          - name: Create site artefact
            uses: actions/upload-artifact@v4
            with:
                name: website-de
                path: de/.output
    deploy:
        runs-on: ubuntu-latest
        needs: build
        name: Deploy
        steps:
          - uses: actions/checkout@v4
          - name: Download site artefact
            uses: actions/download-artifact@v4
            with:
                name: website-de
                path: .output
          - name: Deploy
            id: wrangler-deploy
            uses: cloudflare/wrangler-action@v3
            with:
              apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
              accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
              command: pages deploy .output/public --project-name=blueshoe-de
          - uses: actions-ecosystem/action-regex-match@v2
            id: regex-match
            with:
              text: ${{ steps.wrangler-deploy.outputs.command-output }}
              regex: '(https:\/\/.+)'
          - name: comment-pr
            uses: JoseThen/comment-pr@v1.2.0
            with:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              comment: "🚀 Deployed to [${{steps.regex-match.outputs.group1}}](${{ steps.regex-match.outputs.group1 }})\n![deploy](https://giphy.com/embed/26u3ZxF1ayvkE755K)"