name: Build & Deploy .io website
on:
    push:
        branches:
        - main

jobs:
    build:
        runs-on: ubuntu-latest
        name: Build
        steps:
          - uses: actions/checkout@v4
          - name: Enable corepack
            run: corepack enable
          - name: Use Node.js
            uses: actions/setup-node@v4
          - name: Build static
            working-directory: io
            run: |
              yarn install
              yarn generate
          - name: Create site artefact
            uses: actions/upload-artifact@v4
            with:
                name: webiste-io
                path: .output
    deploy:
        runs-on: ubuntu-latest
        needs: build
        name: Deploy
        steps:
          - uses: actions/checkout@v4
          - name: Download site artefact
            uses: actions/download-artifact@v4
            with:
                name: website-io
                path: .output
          - name: Deploy
            uses: cloudflare/wrangler-action@v3
            with:
              apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
              accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
              command: pages publish .output/ --project-name=blueshoe-io