name: Build & Deploy .io website
on:
    push:
        branches:
        - main
    pull_request:
      types: [opened, synchronize, reopened]
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        name: Build
        steps:
          - uses: actions/checkout@v4
          - name: Enable corepack
            run: corepack enable
          - name: Use Node.js
            uses: actions/setup-node@v4
          - name: Build static
            working-directory: io
            run: |
              yarn install
              yarn generate
          - name: Copy redirects
            run: cp io/_redirects io/.output/public/_redirects
          - name: Create site artefact
            uses: actions/upload-artifact@v4
            with:
                name: website-io
                path: io/.output
    deploy:
        runs-on: ubuntu-latest
        needs: build
        name: Deploy
        outputs:
          preview-url: ${{ steps.wrangler-deploy.outputs.preview-url }}
        steps:
          - uses: actions/checkout@v4
          - name: Download site artefact
            uses: actions/download-artifact@v4
            with:
                name: website-io
                path: .output
          - id: wrangler-deploy
            name: Deploy
            uses: cloudflare/wrangler-action@v3
            with:
              apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
              accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
              command: pages deploy .output/public --project-name=blueshoe-io
          - name: PR Comment
            uses: github-actions-up-and-running/pr-comment@v1.0.1
            with:
              repo-token: ${{ secrets.GITHUB_TOKEN }}
              message: "Deployed to [blueshoe.io](${{ needs.wrangler-deploy.outputs.preview-url }})"
          
