name: Build & Deploy Histoire
on:
    push:
        branches:
        - main

jobs:
    build:
        runs-on: ubuntu-latest
        name: Build
        steps:
          - uses: actions/checkout@v4
          - name: Use Node.js
            uses: actions/setup-node@v4
          - run: npm ci
          - run: npm run story:build
          - name: Create Histoire artefact
            uses: actions/upload-artifact@v4
            with:
                name: histoire
                path: .histoire/dist
    deploy:
        runs-on: ubuntu-latest
        needs: build
        name: Deploy
        steps:
          - uses: actions/checkout@v4
          - name: Download Histoire artefact
            uses: actions/download-artifact@v4
            with:
                name: histoire
                path: .histoire/dist
          - name: Deploy
            uses: cloudflare/wrangler-action@v3
            with:
              apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
              accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
              command: pages publish .histoire/dist/ --project-name=histoire-blueshoe-io